### ISSUE TITLE
It doesn't display

### ISSUE THREAD

**Issue by TheZ79** [johnjore/hajk#57]
It doesn't display. All references were loaded except the Microsoft.VCLibs reference and it completed the build without any problems. But when I import the map, nothing appears. What could be the problem?

**Comment by TheZ79** [comment]
Debug report is attached

[HajkDebugReport.txt](https://github.com/johnjore/hajk/files/10529323/HajkDebugReport.txt)

**Comment by johnjore** [comment]
Hi and thanks for reaching out, but this project is not in a state where it's suitable for end-users. You would need to do the investigation yourself, and submit a PR to fix the issue.

I hope to resume work on this app in a few months, but right now no work is being done due to other priorities.

John
